// 전국 17개 시도의 과제용 날씨 Mock 데이터
export const weatherList = [
  {
    id: 'seoul',
    mapName: '서울특별시',
    name: '서울',
    fullName: '서울특별시',
    temp: 28,
    high: 31,
    low: 23,
    status: '맑음',
    emoji: '☀️',
    humidity: 48,
    rainChance: 10,
    wind: 2.1,
    popularFoods: ['설렁탕', '떡볶이', '빈대떡'],
  },
  {
    id: 'busan',
    mapName: '부산광역시',
    name: '부산',
    fullName: '부산광역시',
    temp: 26,
    high: 29,
    low: 22,
    status: '구름',
    emoji: '⛅',
    humidity: 64,
    rainChance: 20,
    wind: 3.4,
    popularFoods: ['돼지국밥', '밀면', '씨앗호떡'],
  },
  {
    id: 'daegu',
    mapName: '대구광역시',
    name: '대구',
    fullName: '대구광역시',
    temp: 31,
    high: 34,
    low: 24,
    status: '맑음',
    emoji: '☀️',
    humidity: 42,
    rainChance: 5,
    wind: 1.8,
    popularFoods: ['막창', '뭉티기', '납작만두'],
  },
  {
    id: 'incheon',
    mapName: '인천광역시',
    name: '인천',
    fullName: '인천광역시',
    temp: 24,
    high: 26,
    low: 20,
    status: '비',
    emoji: '🌧️',
    humidity: 78,
    rainChance: 80,
    wind: 4.2,
    popularFoods: ['짜장면', '쫄면', '밴댕이회'],
  },
  {
    id: 'gwangju',
    mapName: '광주광역시',
    name: '광주',
    fullName: '광주광역시',
    temp: 27,
    high: 30,
    low: 22,
    status: '소나기',
    emoji: '🌦️',
    humidity: 73,
    rainChance: 65,
    wind: 2.7,
    popularFoods: ['떡갈비', '상추튀김', '오리탕'],
  },
  {
    id: 'daejeon',
    mapName: '대전광역시',
    name: '대전',
    fullName: '대전광역시',
    temp: 23,
    high: 27,
    low: 19,
    status: '구름',
    emoji: '☁️',
    humidity: 58,
    rainChance: 25,
    wind: 2.2,
    popularFoods: ['칼국수', '두부두루치기', '튀김소보로'],
  },
  {
    id: 'ulsan',
    mapName: '울산광역시',
    name: '울산',
    fullName: '울산광역시',
    temp: 25,
    high: 28,
    low: 21,
    status: '맑음',
    emoji: '🌤️',
    humidity: 61,
    rainChance: 10,
    wind: 3.1,
    popularFoods: ['언양불고기', '물회', '가자미미역국'],
  },
  {
    id: 'sejong',
    mapName: '세종특별자치시',
    name: '세종',
    fullName: '세종특별자치시',
    temp: 22,
    high: 26,
    low: 17,
    status: '구름',
    emoji: '☁️',
    humidity: 56,
    rainChance: 20,
    wind: 1.9,
    popularFoods: ['복숭아', '어죽', '도토리묵'],
  },
  {
    id: 'gyeonggi',
    mapName: '경기도',
    name: '경기',
    fullName: '경기도',
    temp: 24,
    high: 27,
    low: 19,
    status: '비',
    emoji: '🌧️',
    humidity: 76,
    rainChance: 75,
    wind: 3.6,
    popularFoods: ['수원왕갈비', '이천쌀밥', '의정부부대찌개'],
  },
  {
    id: 'gangwon',
    mapName: '강원도',
    name: '강원',
    fullName: '강원특별자치도',
    temp: 8,
    high: 12,
    low: 3,
    status: '눈',
    emoji: '🌨️',
    humidity: 82,
    rainChance: 70,
    wind: 5.1,
    popularFoods: ['닭갈비', '막국수', '감자옹심이'],
  },
  {
    id: 'chungbuk',
    mapName: '충청북도',
    name: '충북',
    fullName: '충청북도',
    temp: 21,
    high: 25,
    low: 16,
    status: '맑음',
    emoji: '🌤️',
    humidity: 51,
    rainChance: 10,
    wind: 1.6,
    popularFoods: ['올갱이국', '도리뱅뱅이', '민물매운탕'],
  },
  {
    id: 'chungnam',
    mapName: '충청남도',
    name: '충남',
    fullName: '충청남도',
    temp: 19,
    high: 23,
    low: 15,
    status: '비',
    emoji: '🌧️',
    humidity: 81,
    rainChance: 85,
    wind: 3.9,
    popularFoods: ['병천순대', '게국지', '어리굴젓'],
  },
  {
    id: 'jeonbuk',
    mapName: '전라북도',
    name: '전북',
    fullName: '전북특별자치도',
    temp: 23,
    high: 27,
    low: 18,
    status: '구름',
    emoji: '⛅',
    humidity: 62,
    rainChance: 30,
    wind: 2.3,
    popularFoods: ['전주비빔밥', '콩나물국밥', '풍천장어'],
  },
  {
    id: 'jeonnam',
    mapName: '전라남도',
    name: '전남',
    fullName: '전라남도',
    temp: 26,
    high: 29,
    low: 21,
    status: '맑음',
    emoji: '☀️',
    humidity: 59,
    rainChance: 10,
    wind: 2.8,
    popularFoods: ['남도한정식', '꼬막정식', '떡갈비'],
  },
  {
    id: 'gyeongbuk',
    mapName: '경상북도',
    name: '경북',
    fullName: '경상북도',
    temp: 29,
    high: 33,
    low: 22,
    status: '맑음',
    emoji: '☀️',
    humidity: 44,
    rainChance: 5,
    wind: 2.5,
    popularFoods: ['안동찜닭', '영주한우', '과메기'],
  },
  {
    id: 'gyeongnam',
    mapName: '경상남도',
    name: '경남',
    fullName: '경상남도',
    temp: 25,
    high: 28,
    low: 20,
    status: '구름',
    emoji: '⛅',
    humidity: 66,
    rainChance: 25,
    wind: 3,
    popularFoods: ['진주냉면', '충무김밥', '아귀찜'],
  },
  {
    id: 'jeju',
    mapName: '제주특별자치도',
    name: '제주',
    fullName: '제주특별자치도',
    temp: 28,
    high: 30,
    low: 24,
    status: '소나기',
    emoji: '🌦️',
    humidity: 77,
    rainChance: 60,
    wind: 4.7,
    popularFoods: ['흑돼지', '고기국수', '갈치조림'],
  },
]

export const findWeatherByMapName = (mapName) =>
  weatherList.find((weather) => weather.mapName === mapName)
